name: Remote update execution
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Redeploy
    runs-on: ubuntu-latest
    steps:
    - name: Docker build and restart on digital ocean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          cd ${{ secrets.BACKEND_APP_DIRECTORY }}
          git pull
          docker build -t telegram-wishlist-backend .
          docker rm -f telegram-wishlist-backend
          docker run -d --name=telegram-wishlist-backend --restart=always -p 8083:8080 \
            -e TELEGRAM_BOT_TOKEN="${{ secrets.TELEGRAM_BOT_TOKEN }}" \
            -e TELEGRAM_MINI_APP_URL="${{ secrets.TELEGRAM_MINI_APP_URL }}" \
            -e PG_HOST="${{ secrets.PG_HOST }}" \
            -e PG_PORT="${{ secrets.PG_PORT }}" \
            -e PG_DATABASE="${{ secrets.PG_DATABASE }}" \
            -e PG_USER="${{ secrets.PG_USER }}" \
            -e PG_PASSWORD="${{ secrets.PG_PASSWORD }}" \
            telegram-wishlist-backend
